version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: dockerstub
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    networks:
      - dockerstub

  db:
    image: mysql:5.7
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - dockerstub

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - dockerstub

networks:
  dockerstub:
    driver: bridge